version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=vuln_bank
      - POSTGRES_USER=vulnbank_su
      - POSTGRES_PASSWORD=vulnbankpass
    ports:
      - "5432:5432"
    networks:
      - vulnnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_NAME=vuln_bank
      - DB_USER=vulnbank_su
      - DB_PASSWORD=vulnbankpass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - vulnnet

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: >
      zap-baseline.py
      -t http://web:4000
      -r zap_baseline_report.html
    networks:
      - vulnnet
    volumes:
      - ./zap-reports:/zap/wrk

  # ⚠️ uncomment untuk ZAP full scan kalau mau
  # zap-full:
  #   image: ghcr.io/zaproxy/zaproxy:stable
  #   command: >
  #     zap-full-scan.py
  #     -t http://web:4000
  #     -r zap_full_report.html
  #   networks:
  #     - vulnnet
  #   volumes:
  #     - ./zap-reports:/zap/wrk

volumes:
  postgres_data:

networks:
  vulnnet:
